# Generated by Django 2.2.1 on 2019-05-27 17:26

import django_partisan.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processor_class', models.CharField(max_length=128)),
                ('priority', models.IntegerField(default=10)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField()),
                ('status', django.contrib.postgres.fields.jsonb.JSONField(default=django_partisan.models.get_default_status)),
            ],
            options={
                'ordering': ('-priority',),
            },
        ),
    ]
