# Generated by Django 2.2.12 on 2020-05-15 03:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_process', 'In Process'), ('error', 'Error'), ('finished', 'Finished')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processor_class', models.CharField(max_length=128)),
                ('priority', models.IntegerField(default=10)),
                ('execute_after', models.DateTimeField(default=django.utils.timezone.now)),
                ('arguments', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-priority',),
            },
        ),
    ]
