# Generated by Django 2.2.12 on 2020-07-21 03:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_partisan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='queue_name',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='extra',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
