DEFAULT_QUEUE_NAME = 'default'


MIN_QUEUE_SIZE = 'MIN_QUEUE_SIZE'
MAX_QUEUE_SIZE = 'MAX_QUEUE_SIZE'
CHECKS_BEFORE_CLEANUP = 'CHECKS_BEFORE_CLEANUP'
WORKERS_COUNT = 'WORKERS_COUNT'
SLEEP_DELAY_SECONDS = 'SLEEP_DELAY_SECONDS'
TASKS_PER_WORKER_INSTANCE = 'TASKS_PER_WORKER_INSTANCE'
DELETE_TASKS_ON_COMPLETE = 'DELETE_TASKS_ON_COMPLETE'
DEFAULT_POSTPONE_DELAY_SECONDS = 'DEFAULT_POSTPONE_DELAY_SECONDS'
DEFAULT_POSTPONES_COUNT = 'DEFAULT_POSTPONES_COUNT'
