import multiprocessing as mp

MIN_QUEUE_SIZE = 2
MAX_QUEUE_SIZE = 10
CHECKS_BEFORE_CLEANUP = 50
WORKERS_COUNT = mp.cpu_count()
SLEEP_DELAY_SECONDS = 2
TASKS_PER_WORKER_INSTANCE = None
DELETE_TASKS_ON_COMPLETE = False
DEFAULT_POSTPONE_DELAY_SECONDS = 5
DEFAULT_POSTPONES_COUNT = 15
